build:
  environment:
    php:
      version: '5.5.14'
      ini:
         'date.timezone': 'UTC'
    hosts:
      www.test.ci: '127.0.0.1'
    java: 'java-7-oracle'
    apache2:
      modules: ['rewrite']
      sites:
        symfony_app:
          web_root: 'web/'
          host: 'www.test.ci'
  cache:
    directories:
      - vendor
      - bin
  dependencies:
    before:
      - 'cp etc/scrutinizer-ci/app/config/parameters.yml app/config/parameters.yml'
      - 'cp etc/scrutinizer-ci/web/app_test.php web/app_test.php'
      - 'cp etc/scrutinizer-ci/web/.htaccess web/.htaccess'
      - 'cp etc/ci/behat.yml behat.yml'
    after:
      - php app/console doctrine:database:create --env=dev
      - php app/console doctrine:database:create --env=test
      - 'php app/console doctrine:migrations:migrate --env=test --no-interaction'
      - 'php app/console doctrine:fixtures:load --env=test --no-interaction'
      - 'php app/console assetic:dump --env=prod --no-debug'
  project_setup:
    before:
      - wget http://selenium-release.storage.googleapis.com/2.50/selenium-server-standalone-2.50.1.jar
      -
        command: java -jar selenium-server-standalone-2.50.1.jar
        background: true
checks:
    php:
        code_rating: true
        duplication: true        
filter:
  paths: [src/*]
tools:
  php_code_sniffer:
    enabled: true
    config:
      standard: ./phpcs.xml
  php_sim: true
  php_changetracking: true
  php_cs_fixer: true
  php_mess_detector:
    enabled: true
    config:
      ruleset: ./phpmd.xml
  php_pdepend: true
  php_analyzer: true
  sensiolabs_security_checker: true
  php_code_coverage: true
