---
parameters:
  deployer_username: vagrant
  php:
    maxfilesize: '20M'
  memcached:
    ip: 127.0.0.1
    port: 11211
  apache:
    port: 81
  applications:
    - name:       user_management_demo
      template:   symfony2-dev-application
      domain:     www.user_management_demo.loc
      path:       /var/www/sites/www.user_management_demo.loc
    - name:       test_user_management_demo
      template:   symfony2-test-application
      domain:     test.user_management_demo.loc
      path:       /var/www/sites/www.user_management_demo.loc
  mysql:
    ip: 127.0.0.1
    root_password: n0p455
  databases:
    - name: user_management_demo_dev
    - name: user_management_demo_test
  database_users:
    - username: user_demo
      password: n0p455
      db_name: user_management_demo_%
  git:
    rate_limit_token:   ADD-YOUR-OWN
  selenium:
    path:       /usr/lib/selenium
    log_path:   /var/log/selenium
    url:        http://selenium-release.storage.googleapis.com/2.50/selenium-server-standalone-2.50.1.jar
    filename:   selenium-server-standalone-2.50.1.jar
  timezone: 'UTC'
