services:
  company_user.facade.simple_user:
    class: Company\UserBundle\Facade\SimpleUserFacade
    arguments: ["@company_user.repository.simple_user","@doctrine.orm.default_entity_manager"]
  company_user.repository.simple_user:
    class: Doctrine\ORM\EntityRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - Company\UserBundle\Entity\SimpleUser