# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

  role_hierarchy:
    ROLE_ADMIN:             ROLE_USER
    ROLE_SUPER_ADMIN:       ROLE_ADMIN

  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    secured_area:
      pattern: ^/admin
      stateless: true
      simple_preauth:
        authenticator: apikey_authenticator
      provider: api_key_user_provider

  providers:
    api_key_user_provider:
      id: api_key_user_provider

  access_control:
    - { path: ^/admin/, role: ROLE_ADMIN }
    - { path: ^/, role: ROLE_USER }