<?php

namespace Company\UserBundle\Repository;

/**
 * SimpleUserRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SimpleUserRepository extends \Doctrine\ORM\EntityRepository
{
}
